Merge UI into Dev
le-rich/DKEngine pull request #11
Opened 2024-09-21 22:32 UTC by baumannkev

Added ImGui windows functionality with dynamic resetting windows after every program shutdown.

2024-09-21 22:35 UTC, le-rich commented
Future PRs should be signed with your name [KB] and your Linear issue ID [COM-XX]

2024-09-21 22:37 UTC, le-rich commented on .github/workflows/branch-and-pr-build-validate.yml
Was this included by accident?

2024-09-21 22:37 UTC, le-rich commented on Physics/test.txt
Lol

2024-09-21 22:39 UTC, baumannkev commented on Physics/test.txt
> +piss on my dry balls
that wasnt me 😆

2024-09-21 22:39 UTC, le-rich requested changes
Changes requested

2024-09-21 22:39 UTC, le-rich commented on UI/main.cpp
This branch is significanty behind master, requesting that you pull latest and merge your changes with it. 

All other projects have also been moved into their own logic/ loops so please integrate into that latest architecture from @Sepehrman and @vinodbandla473

2024-09-21 22:52 UTC, le-rich approved these changes

2024-09-23 05:30 UTC, Tissure submitted a review, later dismissed
lgtm

2024-09-26 00:43 UTC, Tissure approved these changes
lgtm

2024-09-26 06:52 UTC, imnorookie commented on Physics/test.txt
> +piss on my dry balls
LOL sorry.

2024-09-26 06:53 UTC, imnorookie approved these changes
luWuks gUwUd two me!! :333

2024-09-26 16:15 UTC, merged