Feature/com 120 multithread renderer
le-rich/DKEngine pull request #46
Opened 2024-11-08 02:16 UTC by Tissure

2024-11-08 17:25 UTC, Tissure commented
I give up on the scene graph copy for now. 
Race condition with scene graph exists, not currently noticeable.

2024-11-08 17:42 UTC, le-rich requested changes
Very messy accross a lot of files. There's no rush to put this code in so we can take the time to get it right, we can have other people contribute to this branch as well.  Let's not push this in this state.

2024-11-08 17:42 UTC, le-rich commented on Core/src/main.cpp
> +//void framebuffer_size_callback(GLFWwindow* window, int width, int height)
Don't leave dead code

2024-11-08 17:42 UTC, le-rich commented on Core/src/main.cpp
> +        //glfwMakeContextCurrent(window);
Dead code

2024-11-08 17:42 UTC, le-rich commented on Core/src/main.cpp
> +        //glEnable(GL_DEPTH_TEST);
Dead code

2024-11-08 17:42 UTC, le-rich commented on Core/src/main.cpp
> +            //system->Update(deltaTimeFloatSeconds);
Dead Code

2024-11-08 17:42 UTC, le-rich commented on Core/src/main.cpp
This file has weird indentation

2024-11-08 17:42 UTC, le-rich commented on Core/include/Components/TransformComponent.h
> +    TransformComponent(TransformComponent& const);
Weird indentation

2024-11-08 17:42 UTC, le-rich commented on Core/include/Scene.h
> +#include <mutex>
Nitpick: put stdlibs after custom includes

2024-11-08 17:42 UTC, le-rich commented on Core/src/Components/TransformComponent.cpp
Inconsistent indentation in this file

2024-11-08 17:42 UTC, le-rich commented on Rendering/include/Components/CameraComponent.h
> +    //CameraComponent(CameraComponent const&);
Dead Code

2024-11-08 17:42 UTC, le-rich commented on Rendering/include/Renderer.h
> +#include <GLFW/glfw3.h>
Nitpick, stdlibs after custom includes

2024-11-18 04:04 UTC, le-rich commented
This PR should be viewed as the multithreading component only, the rendering needs to undergo another task using renderables.

2024-11-18 04:06 UTC, imnorookie approved these changes
:3

2024-11-18 04:06 UTC, Sepehrman approved these changes

2024-11-18 04:08 UTC, Sepehrman approved these changes

2024-11-18 04:10 UTC, le-rich approved these changes

2024-11-18 04:10 UTC, merged