Feature/com 165 lap system
le-rich/DKEngine pull request #60
Opened 2024-11-18 07:30 UTC by Lukauigi

2024-11-18 09:41 UTC, Tissure requested changes
Scripting changes from me. Gonna let physics handle the AABB.
Also check for merge conflicts before making a PR.

2024-11-18 09:41 UTC, Tissure commented on Game/include/Scripts/LapCheckpointScript.h
> +	void Init(LapManagerScript* lapManager, TransformComponent* other, int checkpointIndex);
Change and override to SetParameters().
Conform to Script.h format and extend ScriptParameters struct.
Use OrbitScript for reference.

2024-11-18 09:41 UTC, Tissure commented on Game/include/Scripts/LapCheckpointScript.h
> +	AE86::Aabb* m_SelfBB = nullptr;
I don't know if you will need these AABB objects. Talk to physics for collision detection.

2024-11-18 09:41 UTC, Tissure commented on Game/include/Scripts/LapManagerScript.h
Conform to Script.h format and extend ScriptParameters struct.
Use OrbitScript for reference.

2024-11-20 03:30 UTC, Tissure approved these changes

2024-11-20 21:22 UTC, imnorookie approved these changes
lgtm :3 thanks 4 the hard work!

2024-11-21 00:16 UTC, merged